London Class 7 - Somayeh Karimi - JavaScript-Core1 - Week 3
CodeYourFuture/JavaScript-Core-1-Coursework-Week3 pull request #60
Opened 2021-02-06 20:51 UTC by DibaKarimi

# Your Details

- Your Name:Somayeh Karimi
- Your City: London
- Your Slack Name: Somayeh Kr

# Homework Details

- Module: JavaScript - Core 1 
- Week: 3

2021-02-07 02:01 UTC, akbasmustafa requested changes

2021-02-07 02:01 UTC, akbasmustafa commented on 1-exercises/A-array-find/exercise.js
> +  return name[0] === "A";
Great work, I think you need to check length of name AND 'A' check

2021-02-13 07:18 UTC, Buroni reviewed
Great job Somayeh! Clean code, good understanding of array methods, and all of your tests pass except one. See below for feedback comments.

2021-02-13 07:18 UTC, Buroni commented on 1-exercises/J-string-substring/exercise2.js
> +names[4] = names[4].substring(0,names[4].split(" ")[0].length);
The expression `names[index].split(" ")[0].length` is repeated 5 times here -- can you think of a way to put it in a re-usable function?

2021-02-13 07:18 UTC, Buroni commented on 2-mandatory/1-oxygen-levels.js
> +  let oxygenLevel =oxygenLevels.map(level => parseFloat(level.substring(0, level.length - 1)));
Nice!

One note for improvement -- `oxygenLevel` isn't a clear variable name. A better name could be `oxygenLevelNumbers`, as you are mapping the percentage strings onto an array of numbers.

2021-02-13 07:18 UTC, Buroni commented on 2-mandatory/3-space-colonies.js
> +  );
Very clear and good use of `substring`

2021-02-13 07:18 UTC, Buroni commented on 2-mandatory/7-password-validator.js
>  function test(test_name, actual, expected) {
Your final test case fails here

2021-05-14 01:59 UTC, closed without merging